version: "3.8"

services:
  stockly:
    container_name: stockly
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: stockly
      POSTGRES_USER: stockly
      POSTGRES_DB: stockly-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
